import { Poppins, Geist } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cookies } from "next/headers";
import Script from "next/script";
import AppThemeProvider from "@/components/theme";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const popins = Poppins({
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "getLancer - A freelancing website",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  const cookieStore = await cookies();

  const theme = cookieStore.get("__theme__")?.value || "system";

  return (
    <html className={cn(theme, "font-sans", geist.variable)} lang="en" style={theme !== "system" ? { colorScheme: theme } : {}} suppressHydrationWarning>
      <body className={popins.className}>
          <AppThemeProvider
            attribute="class"
            defaultTheme={theme}
            enableSystem
          >
            <SessionProvider session={session}>
              <Navbar />
              <div className="container mx-auto min-h-screen">
                {children}

              </div>
              <Footer />
              <Toaster />
            </SessionProvider>
          </AppThemeProvider>

          {process.env.E2E_TEST !== "1" && (
            <Script
              src="https://challenges.cloudflare.com/turnstile/v0/api.js"
              strategy="afterInteractive"
            />
          )}
      </body>
    </html>
  );
}
