import { Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const popins = Poppins({
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "getLancer - A freelancing website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={popins.className}>
        <Navbar/>
        <div className="container mx-auto min-h-[87.8vh]">
            {children}
          </div>
        <Footer/>
      </body>
    </html>
  );
}
